batch_size: 8
collate: batch
device: cuda
execution:
  epochs_completed: 8
  local_start: 2022-05-14_18:03:03
  local_stop: 2022-05-15_05:37:23
  program_exit: FAILURE
  stats:
    train_acc: 0.18756824634199606
    train_loss: 2.240276473347967
    val_acc: 0.1953365089121082
    val_loss: 2.448488049552568
model:
  act_func: relu
  block: DeepLPBlock
  classname: LPResNet
  num_blocks: 7
  num_params: 661322
  out_classes: 10
  type: lp_resnet
num_epochs: 40
optimizer:
  params:
    lr: 0.001
  type: adam
out_dir: /geode2/home/u080/skarukas/Carbonate/SITH/out/LP_ResNet_train/rotsvhn/resnets_nofirst_layer_470915/resnet44_2
param: param-files/LPResNet/RotSVHN/resnet44.yaml
train_data_dir:
  kwargs:
    root: data
    split: train
  type: RotSVHN
val_data_dir:
  kwargs:
    root: data
    split: test
  type: RotSVHN
