batch_size: 32
collate: batch
device: cuda
execution:
  epochs_completed: 15
  local_start: 2022-04-02_10:39:56
  local_stop: 2022-04-02_12:44:23
  program_exit: FAILURE
  stats:
    train_acc: 0.7654750479846449
    train_loss: 0.6649215983337724
    val_acc: 0.716952875399361
    val_loss: 0.8122034205224948
model:
  act_func: relu
  batch_norm: false
  classname: DeepLogPolarClassifier
  dropout: 0.2
  layer_params:
  - in_channels: 3
    k: 35
    kernel_size:
    - 7
    - 7
    ntau: 30
    num_angles: 20
    out_channels: 16
    stride: 2
    tau_max: 40
    tau_min: 1
    tau_pooling: 4
    theta_pooling: 4
  - in_channels: 16
    k: 35
    kernel_size:
    - 7
    - 7
    ntau: 30
    num_angles: 20
    out_channels: 32
    stride: 2
    tau_max: 20
    tau_min: 1
    tau_pooling: 4
    theta_pooling: 4
  - in_channels: 32
    k: 35
    kernel_size:
    - 7
    - 7
    ntau: 30
    num_angles: 20
    out_channels: 64
    stride: 2
    tau_max: 10
    tau_min: 1
    tau_pooling: 4
    theta_pooling: 4
  num_params: 185562
  out_classes: 10
  output: max
  type: logpolar
num_epochs: 40
optimizer:
  params:
    lr: 0.001
  type: adam
out_dir: /geode2/home/u080/skarukas/Carbonate/SITH/out/Deep_LP_train/cifar10/ntau_ab_7x7_1239055/tau30_2
param: param-files/Deep-LP/CIFAR10/tau30.yaml
train_data_dir:
  kwargs:
    download: true
    root: data
    train: true
  type: CIFAR10
val_data_dir:
  kwargs:
    download: true
    root: data
    train: false
  type: CIFAR10
