batch_size: 32
collate: batch
device: cuda
execution:
  epochs_completed: 30
  local_start: 2022-04-02_15:06:15
  local_stop: 2022-04-02_20:00:14
  program_exit: FAILURE
  stats:
    train_acc: 0.7575575815738963
    train_loss: 0.6809822063433079
    val_acc: 0.6924920127795527
    val_loss: 0.878162845255087
model:
  act_func: relu
  batch_norm: false
  classname: DeepLogPolarClassifier
  dropout: 0.2
  layer_params:
  - in_channels: 3
    k: 35
    kernel_size:
    - 5
    - 5
    ntau: 26
    num_angles: 20
    out_channels: 16
    stride: 2
    tau_max: 40
    tau_min: 1
    tau_pooling: 4
    theta_pooling: 4
  - in_channels: 16
    k: 35
    kernel_size:
    - 5
    - 5
    ntau: 26
    num_angles: 20
    out_channels: 32
    stride: 2
    tau_max: 40
    tau_min: 1
    tau_pooling: 4
    theta_pooling: 4
  - in_channels: 32
    k: 35
    kernel_size:
    - 5
    - 5
    ntau: 26
    num_angles: 20
    out_channels: 64
    stride: 2
    tau_max: 40
    tau_min: 1
    tau_pooling: 4
    theta_pooling: 4
  num_params: 113370
  out_classes: 10
  output: max
  type: logpolar
num_epochs: 40
optimizer:
  params:
    lr: 0.003
  type: adam
out_dir: /geode2/home/u080/skarukas/Carbonate/SITH/out/Deep_LP_train/cifar10/learningrate_ab_1240860/3e-3_lr_1
param: param-files/Deep-LP/CIFAR10/ab_tests/3e-3_lr.yaml
train_data_dir:
  kwargs:
    download: true
    root: data
    train: true
  type: CIFAR10
val_data_dir:
  kwargs:
    download: true
    root: data
    train: false
  type: CIFAR10
