batch_size: 16
collate: batch
device: cuda
execution:
  epochs_completed: 0
  local_start: 2022-05-06_19:53:19
  local_stop: 2022-05-06_19:53:26
  program_exit: FAILURE
model:
  act_func: relu
  batch_norm: false
  classname: DeepLogPolarClassifier
  dropout: 0.2
  layer_params:
  - in_channels: 1
    kernel_size: 7
    lp_version: bilinear
    ntau: 20
    num_angles: 12
    out_channels: 32
    relative_encoding: true
    tau_max: 30
    tau_min: 1
  - in_channels: 32
    kernel_size: 5
    lp_version: bilinear
    ntau: 20
    num_angles: 12
    out_channels: 32
    relative_encoding: true
    tau_max: 30
    tau_min: 1
  - in_channels: 32
    kernel_size: 5
    lp_version: bilinear
    ntau: 20
    num_angles: 12
    out_channels: 32
    relative_encoding: true
    tau_max: 30
    tau_min: 1
  num_params: 62410
  out_classes: 10
  output: max
  type: logpolar
num_epochs: 40
optimizer:
  params:
    lr: 0.001
  type: adam
out_dir: /geode2/home/u080/skarukas/Carbonate/SITH/out/Deep_LP_train/mnist/debug_relative_encoding_450270/standard_relative_all_1
param: param-files/Deep-LP/MNIST/rotation_test/standard_relative_all.yaml
train_data_dir:
  kwargs:
    root: data
    train: true
  type: FastMNIST
val_data_dir:
  kwargs:
    root: data
    train: false
  type: FastMNIST
