batch_size: 32
collate: batch
device: cuda
execution:
  epochs_completed: 40
  local_start: 2022-03-26_17:37:29
  local_stop: 2022-03-26_21:24:20
  program_exit: SUCCESS
  stats:
    train_acc: 0.7531190019193857
    train_loss: 0.696103100927686
    val_acc: 0.5819688498402555
    val_loss: 1.3761601071007334
model:
  act_func: relu
  batch_norm: false
  classname: DeepLogPolarClassifier
  layer_params:
  - in_channels: 3
    k: 35
    kernel_size:
    - 5
    - 5
    ntau: 40
    num_angles: 10
    out_channels: 16
    stride: 2
    tau_max: 20
    tau_min: 1
    theta_pooling: 2
  - in_channels: 16
    k: 35
    kernel_size:
    - 5
    - 5
    ntau: 40
    num_angles: 10
    out_channels: 32
    stride: 2
    tau_max: 20
    tau_min: 1
    theta_pooling: 2
  - in_channels: 32
    k: 35
    kernel_size:
    - 5
    - 5
    ntau: 40
    num_angles: 10
    out_channels: 64
    stride: 2
    tau_max: 20
    tau_min: 1
    theta_pooling: 2
  num_params: 74970
  out_classes: 10
  type: logpolar
num_epochs: 40
optimizer:
  params:
    lr: 0.001
  type: adam
out_dir: /geode2/home/u080/skarukas/Carbonate/SITH/out/Deep_LP_train/cifar10/centerout_lowmaxtau_1219162/centerout-larger_2
param: param-files/Deep-LP/CIFAR10/centerout-larger.yaml
train_data_dir:
  kwargs:
    download: true
    root: data
    train: true
  type: CIFAR10
val_data_dir:
  kwargs:
    download: true
    root: data
    train: false
  type: CIFAR10
