batch_size: 16
collate: batch
device: cuda
execution:
  epochs_completed: 40
  local_start: 2022-04-27_20:15:17
  local_stop: 2022-04-28_01:22:34
  program_exit: SUCCESS
  stats:
    train_acc: 0.9958666666666667
    train_loss: 0.013970213438972234
    val_acc: 0.9918
    val_loss: 0.024978265314373856
model:
  act_func: relu
  batch_norm: false
  classname: DeepLogPolarClassifier
  dropout: 0.2
  layer_params:
  - in_channels: 1
    kernel_size: 7
    ntau: 8
    num_angles: 12
    out_channels: 32
    spatial_pooling: 2
    tau_max: 30
    tau_min: 1
    topk: 12
  - in_channels: 32
    kernel_size: 5
    ntau: 8
    num_angles: 12
    out_channels: 32
    spatial_pooling: 2
    tau_max: 30
    tau_min: 1
    topk: 12
  - in_channels: 32
    kernel_size: 5
    ntau: 8
    num_angles: 12
    out_channels: 32
    spatial_pooling: 2
    tau_max: 30
    tau_min: 1
    topk: 12
  num_params: 81354
  out_classes: 10
  output: max
  type: logpolar
num_epochs: 40
optimizer:
  params:
    lr: 0.001
  type: adam
out_dir: /geode2/home/u080/skarukas/Carbonate/SITH/out/Deep_LP_train/mnist/full_mnist_angle_invariance/bilinear_trim_spool_415141/30deg_rotations_tk12_pool_1
param: param-files/Deep-LP/MNIST/rotation_test/30deg_rotations_tk12_pool.yaml
train_data_dir:
  kwargs:
    root: data
    train: true
  type: FastMNIST
val_data_dir:
  kwargs:
    root: data
    train: false
  type: FastMNIST
