batch_size: 32
collate: batch
device: cuda
execution:
  epochs_completed: 40
  local_start: 2022-03-17_15:35:37
  local_stop: 2022-03-17_21:22:32
  program_exit: SUCCESS
  stats:
    train_acc: 0.9919166666666667
    train_loss: 0.0248903303360518
    val_acc: 0.9862220447284346
    val_loss: 0.051596268036832996
model:
  act_func: relu
  batch_norm: false
  classname: DeepLogPolarClassifier
  layer_params:
  - in_channels: 1
    k: 35
    kernel_size:
    - 5
    - 5
    ntau: 40
    num_angles: 10
    out_channels: 20
    stride: 2
    tau_max: 60
    tau_min: 1
    theta_pooling: 2
  - in_channels: 20
    k: 35
    kernel_size:
    - 5
    - 5
    ntau: 40
    num_angles: 10
    out_channels: 20
    stride: 2
    tau_max: 60
    tau_min: 1
    theta_pooling: 2
  num_params: 13570
  out_classes: 10
  output: max
  type: logpolar
num_epochs: 40
optimizer:
  params:
    lr: 0.001
  type: adam
out_dir: /geode2/home/u080/skarukas/Carbonate/SITH/out/Deep_LP_train/lp_mnist_output_ab_1190957/maxout-med
param: param-files/Deep-LP/maxout-med.yaml
train_data_dir:
  kwargs:
    root: data
    train: true
  type: FastMNIST
val_data_dir:
  kwargs:
    root: data
    train: false
  type: FastMNIST
