batch_size: 16
collate: batch
device: cuda
execution:
  epochs_completed: 40
  local_start: 2022-05-03_13:36:37
  local_stop: 2022-05-03_20:33:42
  program_exit: SUCCESS
  stats:
    train_acc: 0.9899666666666667
    train_loss: 0.030729918176014632
    val_acc: 0.9828
    val_loss: 0.0495176584853034
model:
  act_func: relu
  batch_norm: false
  classname: DeepLogPolarClassifier
  dropout: 0.2
  layer_params:
  - in_channels: 1
    kernel_size: 7
    lp_version: bilinear
    ntau: 20
    num_angles: 12
    out_channels: 32
    tau_max: 30
    tau_min: 1
    topk: 12
  - in_channels: 32
    kernel_size: 5
    lp_version: bilinear
    ntau: 20
    num_angles: 12
    out_channels: 32
    tau_max: 30
    tau_min: 1
    topk: 12
  - in_channels: 32
    kernel_size: 5
    lp_version: bilinear
    ntau: 20
    num_angles: 12
    out_channels: 32
    tau_max: 30
    tau_min: 1
    topk: 12
  num_params: 81354
  out_classes: 10
  output: max
  type: logpolar
num_epochs: 40
optimizer:
  params:
    lr: 0.001
  type: adam
out_dir: /geode2/home/u080/skarukas/Carbonate/SITH/out/Deep_LP_train/mnist_r/bilinear_trim_new_442476/standard_mr_0
param: param-files/Deep-LP/MNIST/rotation_test/standard_mr.yaml
train_data_dir:
  kwargs:
    root: data
    train: true
  type: MNIST_R
val_data_dir:
  kwargs:
    root: data
    train: false
  type: MNIST_R
