batch_size: 8
collate: batch
device: cuda
execution:
  epochs_completed: 17
  local_start: 2022-04-28_14:30:28
  local_stop: 2022-04-28_23:01:09
  program_exit: FAILURE
  stats:
    train_acc: 0.9857
    train_loss: 0.047599440264910586
    val_acc: 0.9841
    val_loss: 0.051191077241962195
model:
  act_func: relu
  batch_norm: false
  classname: DeepLogPolarClassifier
  dropout: 0.2
  layer_params:
  - in_channels: 1
    kernel_size: 7
    lp_version: bilinear
    ntau: 20
    num_angles: 12
    out_channels: 32
    tau_max: 30
    tau_min: 1
    topk: 12
  - in_channels: 32
    kernel_size: 5
    lp_version: bilinear
    ntau: 20
    num_angles: 12
    out_channels: 64
    tau_max: 30
    tau_min: 1
    topk: 12
  - in_channels: 32
    kernel_size: 5
    lp_version: bilinear
    ntau: 20
    num_angles: 12
    out_channels: 64
    tau_max: 30
    tau_min: 1
    topk: 12
  num_params: 148746
  out_classes: 10
  output: max
  type: logpolar
num_epochs: 40
optimizer:
  params:
    lr: 0.001
  type: adam
out_dir: /geode2/home/u080/skarukas/Carbonate/SITH/out/Deep_LP_train/mnist_r/full_mnist_angle_invariance/bilinear_ntau20_421074/30deg_rotations_tk12_lg_1
param: param-files/Deep-LP/MNIST/rotation_test/30deg_rotations_tk12_lg.yaml
train_data_dir:
  kwargs:
    root: data
    train: true
  type: MNIST_R
val_data_dir:
  kwargs:
    root: data
    train: false
  type: MNIST_R
