batch_size: 32
collate: batch
device: cuda
execution:
  epochs_completed: 24
  local_start: 2022-03-26_17:41:04
  local_stop: 2022-03-27_02:21:18
  program_exit: FAILURE
  stats:
    train_acc: 0.7484604926423545
    train_loss: 0.7115308485844162
    val_acc: 0.6649361022364217
    val_loss: 0.992788378042154
model:
  act_func: relu
  batch_norm: false
  classname: DeepLogPolarClassifier
  layer_params:
  - in_channels: 3
    k: 35
    kernel_size:
    - 5
    - 5
    ntau: 40
    num_angles: 10
    out_channels: 20
    stride: 2
    tau_max: 60
    tau_min: 1
    tau_pooling: 4
    theta_pooling: 2
  - in_channels: 20
    k: 35
    kernel_size:
    - 5
    - 5
    ntau: 40
    num_angles: 10
    out_channels: 20
    stride: 2
    tau_max: 60
    tau_min: 1
    tau_pooling: 4
    theta_pooling: 2
  num_params: 38570
  out_classes: 10
  output: max
  type: logpolar
num_epochs: 40
optimizer:
  params:
    lr: 0.001
  type: adam
out_dir: /geode2/home/u080/skarukas/Carbonate/SITH/out/Deep_LP_train/cifar10/maxout_less_pooling_1219247/maxout-med_0
param: param-files/Deep-LP/CIFAR10/maxout-med.yaml
train_data_dir:
  kwargs:
    download: true
    root: data
    train: true
  type: CIFAR10
val_data_dir:
  kwargs:
    download: true
    root: data
    train: false
  type: CIFAR10
