batch_size: 32
collate: batch
device: cuda
execution:
  epochs_completed: 18
  local_start: 2022-04-02_23:09:45
  local_stop: 2022-04-03_03:56:31
  program_exit: FAILURE
  stats:
    train_acc: 0.7636956174024312
    train_loss: 0.6678476857303887
    val_acc: 0.7019768370607029
    val_loss: 0.8616696234328297
model:
  act_func: relu
  batch_norm: false
  classname: DeepLogPolarClassifier
  dropout: 0.2
  layer_params:
  - in_channels: 3
    k: 35
    kernel_size:
    - 7
    - 7
    ntau: 26
    num_angles: 20
    out_channels: 16
    stride: 2
    tau_max: 40
    tau_min: 1
    tau_pooling: 4
    theta_pooling: 4
  - in_channels: 16
    k: 35
    kernel_size:
    - 7
    - 7
    ntau: 26
    num_angles: 20
    out_channels: 32
    stride: 2
    tau_max: 40
    tau_min: 1
    tau_pooling: 4
    theta_pooling: 4
  - in_channels: 32
    k: 35
    kernel_size:
    - 7
    - 7
    ntau: 26
    num_angles: 20
    out_channels: 64
    stride: 2
    tau_max: 40
    tau_min: 1
    tau_pooling: 4
    theta_pooling: 4
  num_params: 175962
  out_classes: 10
  output: max
  type: logpolar
num_epochs: 40
optimizer:
  params:
    lr: 0.001
  type: adam
out_dir: /geode2/home/u080/skarukas/Carbonate/SITH/out/Deep_LP_train/cifar10/filtersize_ab_1240919/7x7_3
param: param-files/Deep-LP/CIFAR10/ab_tests/7x7.yaml
train_data_dir:
  kwargs:
    download: true
    root: data
    train: true
  type: CIFAR10
val_data_dir:
  kwargs:
    download: true
    root: data
    train: false
  type: CIFAR10
