batch_size: 32
collate: batch
device: cuda
execution:
  epochs_completed: 12
  local_start: 2022-03-07_15:54:30
  local_stop: 2022-03-07_16:53:51
  program_exit: FAILURE
  stats:
    train_acc: 0.9503833333333334
    train_loss: 0.1581093621139725
    val_acc: 0.9506789137380192
    val_loss: 0.1489756555942158
model:
  act_func: relu
  batch_norm: false
  classname: DeepLogPolarClassifier
  layer_params:
  - in_channels: 1
    k: 35
    kernel_size:
    - 5
    - 5
    ntau: 40
    num_angles: 10
    out_channels: 5
    stride: 2
    tau_max: 60
    tau_min: 1
    theta_pooling: 2
  - in_channels: 10
    k: 35
    kernel_size:
    - 5
    - 5
    ntau: 40
    num_angles: 10
    out_channels: 10
    stride: 2
    tau_max: 60
    tau_min: 1
    theta_pooling: 2
  num_params: 3410
  out_classes: 10
  type: logpolar
num_epochs: 40
optimizer:
  params:
    lr: 0.001
  type: adam
out_dir: /geode2/home/u080/skarukas/Carbonate/SITH/out/Deep_LP_train/lp_mnist_small_1153327/0
param: param-files/Deep-LP/log-polar-params-1.yaml
train_data_dir:
  kwargs:
    root: data
    train: true
  type: FastMNIST
val_data_dir:
  kwargs:
    root: data
    train: false
  type: FastMNIST
